/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestionpedidos.igu;

import com.gestionpedidos.logica.Controladora;
import com.gestionpedidos.logica.Pedido;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CrearPedidoRestaurante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearPedidoRestaurante.class.getName());
    
    private void limpiarFormulario(){
        txtNombrePlato.setText("");
        txtDireccionEntrega.setText("");
        txtCantidadPlatos.setText("");
        cmbCategoriaPlato.setSelectedIndex(0);
        buttonGroup1.clearSelection();
    }
    
    private boolean validarFormulario() {

        // VALIDACIÓN DEL NOMBRE PLATO
        String nombre = txtNombrePlato.getText().trim();
        if(nombre.isEmpty()){

            JOptionPane.showMessageDialog(this, "El nombre del plato es obligatorio");
            txtNombrePlato.requestFocus();
            return false;
        }
        if(!nombre.matches("[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ ]+")){

            JOptionPane.showMessageDialog(this, "Solo se permiten letras y números en el nombre del plato");
            return false;
        }
        
        //VALIDACIÓN DE LA CATEGORÍA
        if(cmbCategoriaPlato.getSelectedIndex() == 0){

            JOptionPane.showMessageDialog(this,
                    "Seleccione una categoría");

            return false;
        }
        
        //VALIDACIÓN DE LA CANTIDAD
        int cantidad;
        try{

            cantidad = Integer.parseInt(txtCantidadPlatos.getText());

            if(cantidad <= 0){

                JOptionPane.showMessageDialog(this,"La cantidad debe ser positiva");
                return false;
            }

        }catch(NumberFormatException e){

            JOptionPane.showMessageDialog(this,"La cantidad debe ser numérica");
            return false;
        }
        
        //VALIDAR TIPO ENTREGA
        if(!rbDomicilio.isSelected() && !rbRecogida.isSelected()){

             JOptionPane.showMessageDialog(this, "Seleccione método de entrega");

             return false;
        }
        
        //VALIDAR DIRECCIÓN ENTREGA
        String direccion = txtDireccionEntrega.getText().trim();
        if(rbDomicilio.isSelected() && direccion.isEmpty()){

            JOptionPane.showMessageDialog(this,
                    "Ingrese dirección de entrega");

            return false;
        }
        
        return true;
    }

    /**
     * Creates new form CrearPedidoRestaurante
     */
    public CrearPedidoRestaurante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombrePlato = new javax.swing.JTextField();
        cmbCategoriaPlato = new javax.swing.JComboBox<>();
        txtCantidadPlatos = new javax.swing.JTextField();
        rbDomicilio = new javax.swing.JRadioButton();
        rbRecogida = new javax.swing.JRadioButton();
        txtDireccionEntrega = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnVerPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("FORMULARIO");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/redimensionlamolinacrearpedido.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setText("Nombre Plato");

        jLabel4.setText("Categoría Plato");

        jLabel5.setText("Cantidad Platos");

        jLabel6.setText("Método Entrega");

        jLabel7.setText("Dirección Entrega");

        txtNombrePlato.addActionListener(this::txtNombrePlatoActionPerformed);

        cmbCategoriaPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Entrante", "Plato Principal", "Postre" }));

        buttonGroup1.add(rbDomicilio);
        rbDomicilio.setText("Domicilio");
        rbDomicilio.addActionListener(this::rbDomicilioActionPerformed);

        buttonGroup1.add(rbRecogida);
        rbRecogida.setText("Recogida");

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        btnMenu.setText("Menú");
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        btnVerPedidos.setText("Ver Pedidos");
        btnVerPedidos.addActionListener(this::btnVerPedidosActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txtNombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCategoriaPlato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCantidadPlatos)
                                    .addComponent(txtDireccionEntrega)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbRecogida)
                                            .addComponent(rbDomicilio))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerPedidos)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCategoriaPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidadPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbDomicilio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbRecogida)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccionEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(btnVerPedidos))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePlatoActionPerformed

    private void rbDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDomicilioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        
        // VALIDAR FORMULARIO
        if(!validarFormulario()){
            return;
        }
        
        // OBTENER DATOS
        String nombre = txtNombrePlato.getText().trim();
        int cantidad = Integer.parseInt( txtCantidadPlatos.getText());
        String direccion = txtDireccionEntrega.getText().trim();
        //OBTENER LA CONFIRMACIÓN DEL PEDIDO
        String metodoEntrega = "";
        if(rbDomicilio.isSelected()){
            metodoEntrega = "Domicilio";
        }else{
            metodoEntrega = "Recogida";
        }
        
        //CREAR OBJETO PEDIDO
        Pedido pedido = new Pedido(
                nombre,
                cmbCategoriaPlato.getSelectedItem().toString(),
                cantidad,
                metodoEntrega,
                direccion
        );
        
        //GUARDAR PEDIDO EN MEMORIA
        Controladora control = new Controladora();
        control.guardarPedido(pedido);
        //MOSTRAR MENSAJE
        JOptionPane.showMessageDialog(this, "Pedido registrado correctamente");
        //LIMPIAR EL FORMULARIO
        limpiarFormulario();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        PrincipalRestaurante pantalla = new PrincipalRestaurante();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPedidosActionPerformed
        // TODO add your handling code here:
        VerPedidoRestaurante pantalla = new VerPedidoRestaurante();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVerPedidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnVerPedidos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCategoriaPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbDomicilio;
    private javax.swing.JRadioButton rbRecogida;
    private javax.swing.JTextField txtCantidadPlatos;
    private javax.swing.JTextField txtDireccionEntrega;
    private javax.swing.JTextField txtNombrePlato;
    // End of variables declaration//GEN-END:variables
}
